name: 'Test Reports'

on:
  workflow_call:

env:
  BUILD_ARTIFACT_ID: ${{github.repository}}-${{ github.ref_name }}-${{ github.run_number }}
  TESTS_ARTIFACT_ID: ${{github.repository}}-${{ github.ref_name }}-${{ github.run_number }}-tests

jobs:
  test_results:
    runs-on: ubuntu-latest
    steps:

      - name: Download test results
        uses: actions/download-artifact@v3
        with:
          name: 

      - uses: dorny/test-reporter@v1
        with:
          artifact: ${{ TESTS_ARTIFACT_ID}}
          name: VSTest Tests # Name of the check run which will be created
          path: "TestResults/*.trx" # Path to test results (inside artifact .zip)
          reporter: dotnet-trx # Format of test results

  code_coverage:
    runs-on: ubuntu-latest
    steps:
    - name: Download test results
      uses: actions/download-artifact@v3
      with:
        name: ${{ TESTS_ARTIFACT_ID }}

    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverlet/coverage.cobertura.xml
        badge: true
        fail_below_min: false
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
        thresholds: "60 80"

    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md
