
name: 'Test Report'
on: 
  workflow_call:

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - run: ls -la

    - uses: dorny/test-reporter@v1
      with:
        artifact: test-results            # artifact name
        name: VSTest Tests                # Name of the check run which will be created
        path: 'TestResults/*.trx'         # Path to test results (inside artifact .zip)
        reporter: dotnet-trx              # Format of test results